

services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iot_network

  sensor_simulation:
    build: ./sensor_simulation
    container_name: sensor_simulation
    image: sensor_simulation
    depends_on:
      - mqtt_broker
      - telegraf
      - influxdb
    ports:
      - "5001:5000"
    networks:
      - iot_network

  node_red:
    image: nodered/node-red
    container_name: node_red
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    depends_on:
      - mqtt_broker
    networks:
      - iot_network

  influxdb:
    image: influxdb:2.7.10
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
      - DOCKER_INFLUXDB_INIT_ORG=IOT
      - DOCKER_INFLUXDB_INIT_BUCKET=IOT
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - iot_network

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_LOG_LEVEL=error
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - iot_network

  telegraf:
    image: telegraf:1.32.3
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mqtt_broker 
      - influxdb
    networks:
      - iot_network

volumes:
  node_red_data:
  influxdb_data:
  grafana_data:

networks:
  iot_network:
